import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture } from './source-fixture.mjs';
const STEP=1/60, near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
async function rig(){const f=await fixture(),a=f.make();a.ink=0;a.lastFire=99;a.kidT=0;a.intent.fire=true;return{...f,a,r:a.weaponRunner};}
const fire=f=>f.r.update(STEP,{fire:true});
test('#241 an admitted shooter insufficient-use attempt starts recovery stop without ink debit or lastFire reset',async()=>{const f=await rig();let events=[];f.on('ink:dry-use',e=>events.push(e));fire(f);assert.equal(f.a.ink,0);assert.equal(f.a.lastFire,99);near(f.a.s3.recoverStopRemaining,f.a.weapon.inkRecoverStop);assert.equal(events.length,1);assert.equal(events[0].calibrated,true);assert.equal(events[0].source,'normal-ink-lock');f.updateResources(f.a,STEP);assert.equal(f.a.ink,0,'next tick cannot refill');});
test('#241 repeated real failed uses extend the stop even while the empty sound is throttled, without shortening a longer stop',async()=>{const f=await rig();fire(f);f.a.s3.recoverStopRemaining=.1;f.r.cooldown=0;assert.ok(f.r.emptyCd>0);f.G.time+=.1;fire(f);near(f.a.s3.recoverStopRemaining,f.a.weapon.inkRecoverStop);f.a.s3.recoverStopRemaining=2;f.r.cooldown=0;fire(f);near(f.a.s3.recoverStopRemaining,2);});
test('#241 no input, aim changes, or direct audio/notification calls do not register dry-use attempts',async()=>{const f=await rig();f.a.s3.recoverStopRemaining=0;f.a.intent.fire=false;f.r.update(STEP,{fire:false});f.a.aimYaw=2;f.r._empty();assert.equal(f.a.s3.recoverStopRemaining,0);assert.equal(f.a.s3.lastDryInkUse,undefined);});
test('#241 release opens the per-weapon recovery boundary and sufficient ink reaches normal successful-shot ownership',async()=>{const f=await rig();fire(f);const delay=f.a.weapon.inkRecoverStop;for(let i=0;i<Math.round(delay/STEP)-1;i++){f.updateResources(f.a,STEP);near(f.a.ink,0);}f.updateResources(f.a,STEP);assert.ok(f.a.ink>0);f.a.ink=f.a.weapon.inkPerShot;f.r.cooldown=0;fire(f);assert.equal(f.shots.length,1);near(f.a.ink,0);near(f.a.lastFire,0);});
test('#241 held dry attempts follow existing native retry cadence and cannot make ink negative',async()=>{const f=await rig();let count=0;f.on('ink:dry-use',()=>count++);for(let i=0;i<120;i++){f.tick(f.a);assert.ok(f.a.ink>=0);}assert.ok(count>1);assert.ok(f.a.ink<f.a.weapon.inkPerShot);assert.equal(f.shots.length,0);const ink=f.a.ink;f.a.intent.fire=false;f.tick(f.a,60);assert.ok(f.a.ink>ink);});
test('#241 dry attempts use the same per-weapon ink lock and reset retires diagnostic state',async()=>{const f=await rig();f.a.weapon.inkRecoverStop=.75;fire(f);near(f.a.s3.recoverStopRemaining,.75);assert.equal(f.a.s3.lastDryInkUse.calibrated,true);assert.equal(f.a.s3.lastDryInkUse.source,'normal-ink-lock');f.a.reset();assert.equal(f.a.s3.lastDryInkUse,undefined);assert.equal(f.a.s3.recoverStopRemaining,0);});
