import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture } from './source-fixture.mjs';
import { adaptIssue427 } from '../issue-427-adapter.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
async function rig(){const f=await fixture({adaptRuntime:adaptIssue427});const helper=f.make(),killer=f.make(),victim=f.make();helper.team=killer.team=0;victim.team=1;for(const a of [helper,killer,victim])a.netLife=1;f.G.match.mode='turf';return{...f,helper,killer,victim};}
const points=f=>f.helper.s3.flow.score/f.profile.flow.threshold*100;
const mark=(f,source='pointSensor',extra={})=>f.emit('assist:mark',{helper:f.helper,victim:f.victim,source,accepted:true,helperLife:1,victimLife:1,...extra});
const damage=(f,amount=10)=>f.emit('damage',{victim:f.victim,attacker:f.helper,amount,source:'shooter'});
const splat=f=>f.emit('splatted',{victim:f.victim,attacker:f.killer,cause:'shooter'});
test('#544 actual Flow owner awards exactly 14fp for damage independent of amount, once per terminal',async()=>{for(const amount of [1,10,80]){const f=await rig();damage(f,amount);near(points(f),0);splat(f);near(points(f),14);assert.equal(f.helper.stats.assists,1);splat(f);near(points(f),14);assert.equal(f.helper.stats.assists,1);}});
test('#544 accepted Point Sensor and Line Marker marking inputs contribute 4fp without damage disclosure',async()=>{for(const source of ['pointSensor','lineMarker']){const f=await rig(),hp=f.victim.hp,last=f.victim.lastDamage;mark(f,source);near(points(f),0);splat(f);near(points(f),4);assert.equal(f.helper.stats.assists,1);assert.equal(f.victim.hp,hp);assert.equal(f.victim.lastDamage,last);assert.equal(f.victim.s3.revealedUntil,undefined);splat(f);near(points(f),4);}});
test('#544 mixed damage and marking gives only the damage assist, in either event order',async()=>{for(const order of [0,1]){const f=await rig();if(order)damage(f);mark(f);if(!order)damage(f);splat(f);near(points(f),14);assert.equal(f.helper.stats.assists,1);}});
test('#544 rejects unknown, unaccepted, stale-life and expired markings, allies, self and killer assists',async()=>{for(const mode of ['cooler','prediction','old-victim','old-helper','expired','ally','self','killer']){const f=await rig();if(mode==='ally')f.helper.team=1;if(mode==='self')f.helper=f.victim;mark(f,mode==='cooler'?'tacticooler':'pointSensor',mode==='prediction'?{accepted:false}:mode==='old-victim'?{victimLife:0}:mode==='old-helper'?{helperLife:0}:{});if(mode==='expired')f.G.time+=f.profile.flow.assistWindow+1e-4;if(mode==='killer')f.killer=f.helper;splat(f);assert.equal(f.helper.stats.assists,0,mode);}});
test('#544 typed assists cannot activate hidden progress and active extension stays independent',async()=>{for(const source of ['pointSensor','damage']){const f=await rig();f.helper.s3.flow.score=f.profile.flow.threshold-.01;if(source==='damage')damage(f);else mark(f);splat(f);assert.ok(points(f)>100);assert.equal(f.helper.s3.flow.active,false);f.victim.netLife++;f.emit('combat:respawn',{actor:f.victim});Object.assign(f.helper.s3.flow,{active:true,remaining:4,score:0});if(source==='damage')damage(f);else mark(f,'pointSensor',{victimLife:2});splat(f);near(f.helper.s3.flow.remaining,4+f.profile.flow.extension);}});
test('#544 render cadence does not change event-domain assist points',async()=>{const scores=[];for(const hz of [30,60,120,144]){const f=await rig();mark(f);for(let i=0;i<hz;i++)f.G.time+=1/hz;splat(f);scores.push(points(f));}for(const score of scores)near(score,4);});
