import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture } from './source-fixture.mjs';
import { FixedClock } from '../runtime/clock.mjs';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
function launch(f,a,kind){a.form='squid';a.intent.fire=a.intent.sub=false;a.grounded=kind==='floor';a.climbing=kind==='wall';a.submerged=kind==='floor';a.wallN.set(0,0,1);a.intent.move.set(0,0,kind==='floor'?-1:1);a.vel.set(0,0,20);f.beforeActions(a,1/60,true);assert.ok(a.s3.roll);return Math.hypot(a.vel.x,a.vel.z);}
test('#972 kid/fire/sub transitions preserve progressive floor/wall retention but remove armor',async()=>{for(const from of ['floor','wall'])for(const to of ['floor','wall'])for(const transition of ['kid','fire','sub']){const f=await fixture(),a=f.make();close(launch(f,a,from),20);for(let chain=1;chain<=2;chain++){a.form='kid';a.intent.fire=transition==='fire';a.intent.sub=transition==='sub';f.beforeActions(a,1/60,false);assert.equal(a.s3.roll,null);assert.equal(a.s3.actions.armor,null);close(a.s3.actions.chainSpeed,20*.85**(chain-1));close(launch(f,a,to),20*.85**chain);}}});
test('#972 humanoid time expires count/timer/speed together; reset remains fresh',async()=>{const f=await fixture(),a=f.make();launch(f,a,'wall');a.form='kid';for(let tick=0;tick<90;tick++)f.beforeActions(a,1/60,false);assert.equal(a.s3.actions.chain,0);assert.equal(a.s3.actions.chainTimer,0);assert.equal(a.s3.actions.chainSpeed,0);close(launch(f,a,'floor'),20);a.reset();close(launch(f,a,'floor'),20);});
test('#972 full Action Intensify retention remains 1 through ordinary form changes',async()=>{const f=await fixture(),a=f.make();a.s3.modifiers.rollRetention=1;close(launch(f,a,'floor'),20);a.form='kid';f.beforeActions(a,1/60,false);close(launch(f,a,'wall'),20);});
test('#972 existing special and Super Jump cancellation still removes action history speed',async()=>{for(const state of ['specialActive','superJumpState']){const f=await fixture(),a=f.make();launch(f,a,'floor');a[state]={};f.beforeActions(a,1/60,false);assert.equal(a.s3.roll,null);assert.equal(a.s3.actions.chainSpeed,0);}});
test('#972 same fixed-tick form/roll sequence agrees at 30/60/120Hz rendering',async()=>{let reference;for(const hz of [30,60,120]){const f=await fixture(),a=f.make(),clock=new FixedClock(),rows=[];for(let frame=0;frame<hz;frame++)clock.advance(1/hz,()=>{if(clock.ticks===0||clock.ticks===30)launch(f,a,clock.ticks===0?'floor':'wall');else{a.form=clock.ticks<15?'kid':'squid';f.beforeActions(a,1/60,false);}rows.push([a.s3.actions.chain,a.s3.actions.chainTimer,a.s3.actions.chainSpeed]);});if(reference)assert.deepEqual(rows,reference);else reference=rows;}});
