import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture } from './weapon-edgecases-fixture.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
async function setup(){const f=await fixture();f.G.physics.segment=(_a,_b,h)=>{h.hit=false;return h;};const system=new f.Projectiles(new f.THREE.Scene()),owner=f.make('charger'),target=f.make();target.team=1;target.pos.set(0,0,0);target.invuln=0;owner.pos.set(-2,0,0);f.G.actors=[target];return {...f,system,owner,target};}
function sweep(f,y,z,radius=0){const p={prev:new f.THREE.Vector3(-2,y,z),pos:new f.THREE.Vector3(2,y,z),owner:f.owner,team:0,wid:'shooter',size:radius,age:.1};return f.fidelityProjectileTargets(f.system,p).length;}
test('#430 independent profile dimensions preserve the supplied capsule aspect, not terrain radius',async()=>{const f=await setup(),p=f.PLAYER;near(2*(p.s3HumanoidHurtRadius??p.radius),.7);near(p.s3HumanoidHurtHeight??p.height,1.65);near((p.s3HumanoidHurtHeight??p.height)/(2*(p.s3HumanoidHurtRadius??p.radius)),1.65/.7);near(p.radius,.38);near(p.height,1.45);near(p.squidHeight,.55);});
test('#430 actual continuous main projectile sweep matches side/head/foot boundaries independently of bullet radius',async()=>{const f=await setup();for(const bullet of [0,.08,.2]){assert.equal(sweep(f,.8,.35+bullet-.0001,bullet),1);assert.equal(sweep(f,.8,.35+bullet+.0001,bullet),0);assert.equal(sweep(f,1.65+bullet-.0001,0,bullet),1);assert.equal(sweep(f,1.65+bullet+.0001,0,bullet),0);assert.equal(sweep(f,-bullet+.0001,0,bullet),1);assert.equal(sweep(f,-bullet-.0001,0,bullet),0);}});
test('#430 swim shape and visual smoothing remain independent',async()=>{const f=await setup();assert.equal(sweep(f,1.58,0),1);f.target.smoothY=10;assert.equal(sweep(f,1.58,0),1);f.target.form='squid';assert.equal(sweep(f,1.58,0),0);assert.equal(sweep(f,.675,.6749),1);assert.equal(sweep(f,.675,.6751),0);});
test('#430 installed finite Charger flight consumes the same independent human shape',async()=>{for(const offset of [-.0001,.0001]){const f=await setup(),hits=[],collision=f.profile.weaponsFidelityCompletion.weapons.charger.CollisionParam,bullet=Math.max(collision.InitRadiusForPlayer,collision.EndRadiusForPlayer),actualY=1.65+bullet+offset;f.system._muzzle=(_a,out)=>out.set(-2,actualY,0);f.system._aimFrom=(_a,_m,out)=>out.set(1,0,0);f.system.applyHit=(_a,e)=>hits.push(e);f.system.fireCharger(f.owner,f.owner.weapon,1);for(let i=0;i<10;i++)f.system.update(1/60);assert.equal(hits.length,offset<0?1:0);}});
