import test from 'node:test';import assert from 'node:assert/strict';
import {fixture} from './robustness-fixture.mjs';
import {installDisconnectFidelity} from '../../splatoon3/runtime/disconnect-fidelity.mjs';
async function setup(){const f=await fixture();let ended=0;f.G.game={hud:{banner(){}},netMatchEnd(){ended++}};installDisconnectFidelity(f);const s=f.makeSession('p2','host',[['host','Host'],['p2','P2'],['gone','Gone']]);const nm=f.makeNetMatch(s);const a=f.makeActor({nid:1,owner:'gone',remote:true});const m=f.bind(nm,[a]);m.mode='turf';m.duration=180;m.setState=function(s){this.state=s;};return {...f,s,nm,m,a,ended:()=>ended};}
test('migration after guest cancellation timer reaches zero finishes cancellation',async()=>{const f=await setup();f.nm.onMessage('host',{k:'nc',r:6});f.nm.update(6);assert.equal(f.nm.s3NoContestRemaining,0);f.s.hostId='p2';f.s.isHost=true;f.nm.onLeave('host',true);f.nm.update(.1);assert.equal(f.ended(),1);});
test('finished participant remains in immutable result roster after leave',async()=>{const f=await setup();f.m.state='finish';f.a.stats.turf=123;f.nm.onLeave('gone',false);assert.equal(f.m.actors.length,1);assert.equal(f.nm.byNid.get(1),f.a);assert.equal(f.a.s3.disconnected,true);assert.equal(f.a.stats.turf,123);});
test('completed result cannot be replaced by a late no-contest decision',async()=>{const f=await setup();f.m.state='results';f.m.result={winner:0,coverage:[.6,.4]};f.nm.onMessage('host',{k:'nc',r:6});f.nm.onMessage('host',{k:'ncend'});assert.equal(f.ended(),0);assert.equal(f.m.s3NoContest,undefined);});
for(const phase of ['finish','judge','results']) test(`leave during ${phase} preserves roster and receives final statistics`,async()=>{const f=await setup();f.m.state=phase;f.nm.onLeave('gone',false);f.nm.onMessage('host',{k:'res',mode:'turf',cov:[.6,.4],win:0,st:[[1,123,4,2,0,0]]});assert.equal(f.a.stats.turf,123);assert.equal(f.a.stats.splats,4);assert.equal(f.m.actors[0],f.a);assert.equal(f.a.s3.disconnected,true);assert.equal(f.m.s3NoContest,undefined);});
for(const phase of ['init','intro']) test(`leave during ${phase} removes nonparticipant`,async()=>{const f=await setup();f.m.state=phase;f.nm.onLeave('gone',false);assert.equal(f.m.actors.length,0);assert.equal(f.nm.byNid.has(1),false);});
test('pending guest still waits for ncend and new host completes once at positive or zero remaining',async()=>{for(const elapsed of [2,6]){const f=await setup();f.nm.onMessage('host',{k:'nc',r:6});f.nm.update(elapsed);assert.equal(f.ended(),0);f.s.hostId='p2';f.s.isHost=true;f.nm.onLeave('host',true);f.nm.update(6);assert.equal(f.ended(),1);f.nm.update(6);f.nm.onMessage('p2',{k:'ncend'});assert.equal(f.ended(),1);}});
test('zero without a pending no-contest does not end a newly hosted match',async()=>{const f=await setup();f.nm.s3NoContestRemaining=0;f.s.hostId='p2';f.s.isHost=true;f.nm.update(1);assert.equal(f.ended(),0);});
test('no-contest first still outranks a late result and unrelated sender cannot cancel',async()=>{const f=await setup();f.nm.onMessage('intruder',{k:'ncend'});assert.equal(f.ended(),0);f.nm.onMessage('host',{k:'nc',r:6});f.nm.onMessage('host',{k:'res',mode:'turf',cov:[.6,.4],win:0,st:[]});assert.equal(f.m.result,undefined);f.nm.onMessage('host',{k:'ncend'});assert.equal(f.ended(),1);});
test('new NetMatch admits its own no-contest after previous result',async()=>{const f=await setup();f.m.result={winner:0};const nm=f.makeNetMatch(f.s,{id:'next'});f.bind(nm,[]);nm.onMessage('host',{k:'nc',r:6});assert.equal(nm.match.s3NoContest,true);nm.onMessage('host',{k:'ncend'});assert.equal(f.ended(),1);});
