import * as THREE from "three";

export type SurfaceKind = "floor" | "grate" | "rock" | "metal" | "crate" | "spawn";

export interface Box {
  id: number;
  min: THREE.Vector3;
  max: THREE.Vector3;
  kind: SurfaceKind;
  paintFloor: boolean; // top face paintable + score eligible
  paintWalls: boolean; // side faces paintable (climbable when own-inked)
  color: number;
  visual: boolean; // whether to generate render geometry (ramps use their own)
  wallTiles: number[]; // wall tile index per side face (+x,-x,+z,-z), -1 = none
}

export interface RayHit {
  t: number;
  point: THREE.Vector3;
  normal: THREE.Vector3;
  box: Box;
  face: number; // 0:+x 1:-x 2:+y 3:-y 4:+z 5:-z
}

const _tmp = new THREE.Vector3();

export class World {
  boxes: Box[] = [];
  private nextId = 1;
  bounds = new THREE.Box3(new THREE.Vector3(-30, -5, -60), new THREE.Vector3(30, 30, 60));
  killY = -3;

  addBox(
    x0: number, x1: number, z0: number, z1: number, y0: number, y1: number,
    opts: Partial<Omit<Box, "id" | "min" | "max">> = {}
  ): Box {
    const b: Box = {
      id: this.nextId++,
      min: new THREE.Vector3(Math.min(x0, x1), y0, Math.min(z0, z1)),
      max: new THREE.Vector3(Math.max(x0, x1), y1, Math.max(z0, z1)),
      kind: opts.kind ?? "floor",
      paintFloor: opts.paintFloor ?? true,
      paintWalls: opts.paintWalls ?? true,
      color: opts.color ?? 0xc9a37a,
      visual: opts.visual ?? true,
      wallTiles: [-1, -1, -1, -1],
    };
    this.boxes.push(b);
    return b;
  }

  /** Ramp along z or x built from micro-steps (collision) — visual slope mesh is generated by the stage builder. */
  addRamp(
    x0: number, x1: number, z0: number, z1: number, hStart: number, hEnd: number,
    axis: "x" | "z", opts: Partial<Omit<Box, "id" | "min" | "max">> = {}
  ): Box[] {
    const len = axis === "z" ? Math.abs(z1 - z0) : Math.abs(x1 - x0);
    const steps = Math.max(2, Math.ceil(Math.abs(hEnd - hStart) / 0.22));
    const out: Box[] = [];
    for (let i = 0; i < steps; i++) {
      const f0 = i / steps, f1 = (i + 1) / steps;
      const h = hStart + (hEnd - hStart) * f1;
      const base = Math.min(hStart, hEnd) - 0.5;
      let bx0 = x0, bx1 = x1, bz0 = z0, bz1 = z1;
      if (axis === "z") { bz0 = z0 + (z1 - z0) * f0; bz1 = z0 + (z1 - z0) * f1; }
      else { bx0 = x0 + (x1 - x0) * f0; bx1 = x0 + (x1 - x0) * f1; }
      out.push(this.addBox(bx0, bx1, bz0, bz1, base, h, { ...opts, visual: false, paintWalls: false }));
    }
    void len;
    return out;
  }

  /** Highest box top at xz that is <= maxY (used for grounding & nav). */
  groundHeight(x: number, z: number, maxY = 1e9, r = 0): number {
    let best = -Infinity;
    for (const b of this.boxes) {
      if (x + r > b.min.x && x - r < b.max.x && z + r > b.min.z && z - r < b.max.z) {
        if (b.max.y <= maxY + 1e-4 && b.max.y > best) best = b.max.y;
      }
    }
    return best;
  }

  boxAt(x: number, y: number, z: number): Box | null {
    for (const b of this.boxes) {
      if (x >= b.min.x && x <= b.max.x && z >= b.min.z && z <= b.max.z && y >= b.min.y && y <= b.max.y) return b;
    }
    return null;
  }

  /** Slab raycast, returns closest hit. */
  raycast(origin: THREE.Vector3, dir: THREE.Vector3, maxDist: number, out: RayHit): boolean {
    let bestT = maxDist;
    let bestBox: Box | null = null;
    let bestFace = 0;
    const invx = 1 / dir.x, invy = 1 / dir.y, invz = 1 / dir.z;
    for (const b of this.boxes) {
      let tmin = 0, tmax = bestT, face = -1;
      // x
      let t1 = (b.min.x - origin.x) * invx, t2 = (b.max.x - origin.x) * invx;
      let fA = 1, fB = 0;
      if (t1 > t2) { const t = t1; t1 = t2; t2 = t; fA = 0; fB = 1; }
      if (t1 > tmin) { tmin = t1; face = fA; }
      if (t2 < tmax) tmax = t2;
      if (tmin > tmax) continue;
      // y
      t1 = (b.min.y - origin.y) * invy; t2 = (b.max.y - origin.y) * invy; fA = 3; fB = 2;
      if (t1 > t2) { const t = t1; t1 = t2; t2 = t; fA = 2; fB = 3; }
      if (t1 > tmin) { tmin = t1; face = fA; }
      if (t2 < tmax) tmax = t2;
      if (tmin > tmax) continue;
      // z
      t1 = (b.min.z - origin.z) * invz; t2 = (b.max.z - origin.z) * invz; fA = 5; fB = 4;
      if (t1 > t2) { const t = t1; t1 = t2; t2 = t; fA = 4; fB = 5; }
      if (t1 > tmin) { tmin = t1; face = fA; }
      if (t2 < tmax) tmax = t2;
      if (tmin > tmax) continue;
      if (face < 0) continue; // origin inside box
      if (tmin < bestT) { bestT = tmin; bestBox = b; bestFace = face; }
      void fB;
    }
    if (!bestBox) return false;
    out.t = bestT;
    out.box = bestBox;
    out.face = bestFace;
    out.point.copy(origin).addScaledVector(dir, bestT);
    out.normal.set(0, 0, 0);
    switch (bestFace) {
      case 0: out.normal.x = 1; break;
      case 1: out.normal.x = -1; break;
      case 2: out.normal.y = 1; break;
      case 3: out.normal.y = -1; break;
      case 4: out.normal.z = 1; break;
      case 5: out.normal.z = -1; break;
    }
    return true;
  }

  lineOfSight(a: THREE.Vector3, b: THREE.Vector3, hit: RayHit): boolean {
    _tmp.subVectors(b, a);
    const d = _tmp.length();
    if (d < 1e-4) return true;
    _tmp.multiplyScalar(1 / d);
    return !this.raycast(a, _tmp, d, hit);
  }

  /**
   * Move an axis-aligned body (feet position `pos`, half-width r, height h) by delta with
   * per-axis sweep + step-up. Returns collision flags.
   */
  moveBody(pos: THREE.Vector3, r: number, h: number, dx: number, dy: number, dz: number, stepHeight: number,
    res: { hitX: boolean; hitZ: boolean; grounded: boolean; hitHead: boolean; wallNormal: THREE.Vector3; wallBox: Box | null; groundBox: Box | null }) {
    res.hitX = res.hitZ = res.grounded = res.hitHead = false;
    res.wallBox = null; res.groundBox = null;
    res.wallNormal.set(0, 0, 0);
    // vertical
    pos.y += dy;
    for (const b of this.boxes) {
      if (!this.overlapXZ(pos, r, b)) continue;
      if (pos.y < b.max.y && pos.y + h > b.min.y) {
        if (dy <= 0 && pos.y - dy >= b.max.y - 1e-3) { pos.y = b.max.y; res.grounded = true; res.groundBox = b; }
        else if (dy > 0 && pos.y + h - dy <= b.min.y + 1e-3) { pos.y = b.min.y - h; res.hitHead = true; }
      }
    }
    // horizontal x
    this.sweepAxis(pos, r, h, dx, 0, stepHeight, res);
    this.sweepAxis(pos, r, h, 0, dz, stepHeight, res);
    // ground probe (for coyote / slope)
    if (!res.grounded) {
      for (const b of this.boxes) {
        if (!this.overlapXZ(pos, r, b)) continue;
        if (pos.y >= b.max.y - 0.03 && pos.y <= b.max.y + 0.03) { res.grounded = true; res.groundBox = b; pos.y = b.max.y; break; }
      }
    }
  }

  private overlapXZ(pos: THREE.Vector3, r: number, b: Box) {
    return pos.x + r > b.min.x && pos.x - r < b.max.x && pos.z + r > b.min.z && pos.z - r < b.max.z;
  }

  private sweepAxis(pos: THREE.Vector3, r: number, h: number, dx: number, dz: number, stepHeight: number,
    res: { hitX: boolean; hitZ: boolean; wallNormal: THREE.Vector3; wallBox: Box | null }) {
    if (dx === 0 && dz === 0) return;
    pos.x += dx; pos.z += dz;
    for (const b of this.boxes) {
      if (!this.overlapXZ(pos, r, b)) continue;
      if (pos.y + h <= b.min.y + 1e-4 || pos.y >= b.max.y - 1e-4) continue;
      // try step up
      const stepUp = b.max.y - pos.y;
      if (stepUp > 0 && stepUp <= stepHeight && this.canStandAt(pos.x, b.max.y, pos.z, r, h)) { pos.y = b.max.y; continue; }
      // push out
      if (dx !== 0) {
        pos.x = dx > 0 ? b.min.x - r - 1e-3 : b.max.x + r + 1e-3;
        res.hitX = true; res.wallNormal.set(dx > 0 ? -1 : 1, 0, 0); res.wallBox = b;
      } else {
        pos.z = dz > 0 ? b.min.z - r - 1e-3 : b.max.z + r + 1e-3;
        res.hitZ = true; res.wallNormal.set(0, 0, dz > 0 ? -1 : 1); res.wallBox = b;
      }
    }
  }

  canStandAt(x: number, y: number, z: number, r: number, h: number): boolean {
    for (const b of this.boxes) {
      if (x + r > b.min.x && x - r < b.max.x && z + r > b.min.z && z - r < b.max.z) {
        if (y + 0.01 < b.max.y && y + h > b.min.y) return false;
      }
    }
    return true;
  }
}
