import{pathToFileURL}from 'node:url';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {fixture}from './portrait-fixture.mjs';import{boot,composed,STEP}from '../../reliability/tests/pause-fixture.mjs';import{syncPortraitFrame}from '../portrait-guard.mjs';import{adaptQualitySource}from '../adapter.mjs';
function portrait(f,on=true){f.context.innerWidth=on?390:1000;f.context.innerHeight=on?844:600;}
function neutral(m){assert.equal(m._ptr.size,0);assert.equal(m._stick.id,-1);assert.equal(m.moveX,0);assert.equal(m.moveY,0);assert.equal(m.lookDX,0);assert.equal(m.lookDY,0);assert.equal(m.pressed.size,0);assert.equal(m.mapOpen,false);for(const v of Object.values(m.buttons))assert.equal(v,false);}
test('actual installed router rejects every hidden control and overlay drag',async()=>{const f=await fixture();portrait(f);const target={closest:s=>s==='.iwm-rotate'?{}:null};for(const id of ['fire','squid','jump','sub','special','map','gyro','pause']){const b=f.input._box(id);f.down(1,b.x,b.y,{target});f.move(1,b.x+50,b.y+20);f.up(1);neutral(f.input);}for(const x of [30,370]){f.down(2,x,400,{target});f.move(2,x+20,450);f.up(2);neutral(f.input);}assert.equal(f.input.gyro.enabled,false);});
test('entering portrait releases held input; landscape and editor keep native pointer paths',async()=>{const f=await fixture();f.button('fire');assert.equal(f.input.buttons.fire,true);portrait(f);f.move(1,300,500);neutral(f.input);portrait(f,false);f.button('fire');assert.equal(f.input.buttons.fire,true);f.up(1);portrait(f);f.input.editing=true;let n=0;f.input._editDown=()=>n++;f.down(2,200,300);assert.equal(n,1);});
function patchController(h){const s=adaptQualitySource('src/game/match.js',composed('src/game/match.js',true));const a=s.indexOf('  updateController(dt) {'),b=s.indexOf('\n  _judge()',a);h.m.updateController=vm.runInNewContext(`(class {${s.slice(a,b)}}).prototype.updateController`);}
async function matchRig(){const h=await boot(),f=await fixture();h.input.mobile=f.input;h.m.mode='turf';patchController(h);const frame=dt=>{const s=syncPortraitFrame(h.game,h.G,f.context);if(!s.offline)h.frame(s.released?0:dt);};return{h,f,frame};}
test('offline playing and intro suspend10seconds, then resume once without held fire/look',async()=>{for(const state of ['playing','intro']){const{h,f,frame}=await matchRig();h.m.state=state;frame(STEP);const time=h.m.time,t=h.G.time,updates=h.updates.length;h.input.keys.add('KeyW');h.input.mouse.left=true;f.button('fire');portrait(f);for(let i=0;i<600;i++)frame(STEP);assert.equal(h.m.time,time);assert.equal(h.G.time,t);assert.equal(h.updates.length,updates);assert.equal(h.m.paused,false);portrait(f,false);frame(10);assert.equal(h.m.time,time);assert.equal(h.updates.length,updates);frame(STEP);assert.equal(h.updates.length,updates+1);assert.equal(h.actor.intent.fire,false);neutral(f.input);}});
test('online keeps native other actors/projectiles/time running while local input is blocked',async()=>{const{h,f,frame}=await matchRig();h.G.netm={};h.other.intent.fire=true;h.input.keys.add('KeyW');h.input.mouse.left=true;portrait(f);const time=h.m.time;for(let i=0;i<6;i++)frame(STEP);assert(h.m.time<time);assert(h.ownedShots.includes(h.other));assert(!h.ownedShots.includes(h.actor));assert.equal(h.controller.enabled,false);assert.equal(h.actor.intent.move.length(),0);assert.equal(h.m.paused,false);});
test('repeated rotation does not steal explicit pause or leave old controller blocked',async()=>{const{h,f,frame}=await matchRig();h.game.pause();for(let i=0;i<8;i++){portrait(f);frame(STEP);portrait(f,false);frame(STEP);}assert.equal(h.m.paused,true);assert.equal(h.menus.current,'pause');portrait(f);frame(STEP);const old=h.m;h.game.match=null;frame(STEP);assert.equal(old.controller.orientationBlocked,false);});
test('production Game has one explicit fixed-clock gate; missing anchors fail closed',()=>{const s=composed('src/main.js',true),p=adaptQualitySource('src/main.js',s);assert.equal(p.split('syncPortraitFrame(this,G)').length,2);assert(p.includes('if (!portraitFrame.offline) runSimulation(this, portraitFrame.released ? 0 : dt);'));assert.throws(()=>adaptQualitySource('src/main.js',s.replace('    runSimulation(this, dt);','')));});
test('full emitted Game frame gates native Match clock/projectiles and rebases after portrait',{skip:!process.env.INKWAVE_PORTRAIT_SITE},async()=>{
 const path=await import('node:path'),site=path.resolve(process.env.INKWAVE_PORTRAIT_SITE),mods=new Map();let isPortrait=true;
 const cls={contains:n=>n==='iw-touch',toggle(){},add(){},remove(){}},context=vm.createContext({console,performance,URL,URLSearchParams,location:{search:''},innerWidth:390,innerHeight:844,matchMedia:()=>({matches:isPortrait}),document:{documentElement:{classList:cls}}});
 function load(file){if(mods.has(file))return mods.get(file);let code=fs.readFileSync(file,'utf8');if(file===path.join(site,'src/main.js')){const re=/const ([\w$]+)=new ([\w$]+);\1\.boot\(\)\.catch\([\s\S]*$/;const hit=code.match(re);assert(hit);code=code.replace(re,`export { ${hit[2]} as Game };`);}const m=new vm.SourceTextModule(code,{context,identifier:file,initializeImportMeta(meta){meta.url=pathToFileURL(file).href;}});mods.set(file,m);return m;}
 const main=load(path.join(site,'src/main.js'));await main.link((s,m)=>load(s==='three'?path.join(site,'vendor/three/build/three.module.js'):s.startsWith('three/addons/')?path.join(site,'vendor/three/jsm',s.slice(13)):path.resolve(path.dirname(m.identifier),s)));await main.evaluate();
 const G=mods.get(path.join(site,'src/core/ctx.js')).namespace.G,Match=mods.get(path.join(site,'src/game/match.js')).namespace.Match,clock=mods.get(path.join(site,'patches/splatoon3/runtime/clock.mjs')).namespace;clock.installClock({G});const calls={},count=k=>()=>{calls[k]=(calls[k]||0)+1;},vector={copy(){},set(){},getWorldDirection(){return this;}};
 Object.assign(G,{time:0,level:{},teamColors:[{},{}],renderer:{info:{reset(){},render:{}},shadowMap:{}},env:{theme:'day',update(){}},fx:{update(){}},projectiles:{update:count('projectile'),updateArc(){}},paint:{flush(){}},camera:{position:vector,up:vector}});
 const f=Object.create(main.namespace.Game.prototype);f.settings={quality:'high'};f.match=new Match({});f.match.state='playing';f.showcase={fullFrame:false,mode:null,update(){},render(){}};f.R={render(){},grade:{uniforms:{uHurt:{value:0}}}};f.decor={update(){}};f.props={update(){}};f.levelMat={userData:{uniforms:{uTime:{value:0},uSeeOn:{value:0},uSeeA:{value:vector},uSeeB:{value:vector}}}};f.rig={update(){},setMap(){},mapK:0};f._dioFog=()=>{};f.menus={update:count('ui')};f.screenfx={update(){}};f._updateLocalLoops=f._updateAmbience=f._padMenus=()=>{};
 f.input={padPressed:new Set(),pollPad(){},endFrame(){},mobile:{root:{classList:{contains:n=>n==='is-active'}},reset(){},gyro:{discard(){}}}};
 const time=f.match.time;for(let i=0;i<600;i++)f._frame(STEP);assert.equal(f.match.time,time);assert.equal(G.time,0);assert.equal(calls.projectile,undefined);assert.equal(calls.ui,600);isPortrait=false;f._frame(10);assert.equal(f.match.time,time);f._frame(STEP);assert(f.match.time<time);assert.equal(calls.projectile,1);isPortrait=true;G.netm={};f._frame(STEP);assert.equal(calls.projectile,2);assert.equal(f.match.paused,false);
});
test('unpatched native rotate target reaches hidden FIRE as a negative control',async()=>{const f=await fixture({raw:true});portrait(f);const b=f.input._box('fire');f.down(9,b.x,b.y,{target:{closest:()=>null}});assert.equal(f.input.buttons.fire,true);});

test('release after orientation change clears pending gesture before delegated up handler',async()=>{const f=await fixture();f.button('fire');assert(f.input._ptr.size>0);portrait(f);let sawHeld;const up=f.input._up;f.input._up=function(e){sawHeld=this._ptr.size>0;return up.call(this,e);};f.up(1);assert.equal(sawHeld,false);neutral(f.input);});
