import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import{fileURLToPath}from'node:url';
import{studioShadowSize,syncStudioShadow,releaseStudioShadow}from'../showcase-shadow.mjs';
import{adaptSource}from'../../splatoon3/adapter.mjs';import{adaptTouchLayout}from'../../touch-layout/adapter.mjs';import{adaptReliability}from'../../reliability/adapter.mjs';import{adaptQualitySource}from'../adapter.mjs';
const ROOT=fileURLToPath(new URL('../../../',import.meta.url));
async function fixture({baseline=false,built=process.env.INKWAVE_STUDIO_BUILT_SITE}={}){
 const src=path.resolve(built||path.join(ROOT,'inkwave-public')),mods=new Map();const context=vm.createContext({console,performance,innerWidth:1280,innerHeight:720,document:{createElement:()=>({width:0,height:0,getContext:()=>({createImageData:(w,h)=>({data:new Uint8Array(w*h*4)}),putImageData(){}})})}});
 function load(file){if(mods.has(file))return mods.get(file);let code=fs.readFileSync(file,'utf8');const rel=path.relative(src,file);if(!built&&!rel.startsWith('..')){code=adaptReliability(rel,adaptTouchLayout(rel,adaptSource(rel,code)));if(!baseline)code=adaptQualitySource(rel,code);}const m=new vm.SourceTextModule(code,{context,identifier:file});mods.set(file,m);return m;}
 const entry=new vm.SourceTextModule("export * from './src/core/ctx.js';export * from './src/config.js';export * from './src/game/showcase.js';export * as THREE from 'three';",{context,identifier:path.join(src,'fixture.mjs')});
 await entry.link((spec,from)=>{let f=spec==='three'?path.join(src,'vendor/three/build/three.module.js'):spec.startsWith('three/addons/')?path.join(src,'vendor/three/jsm',spec.slice(13)):path.resolve(path.dirname(from.identifier),spec);if(!built)f=f.replace('/inkwave-public/patches/','/patches/');return load(f);});await entry.evaluate();return entry.namespace;
}
function rig(f,quality='low',mobile={touch:false}){const{G,THREE,Showcase}=f;G.settings={quality};G.game={mobile};const sc=Object.create(Showcase.prototype);sc.scene=new THREE.Scene();sc._buildLights();Object.assign(sc,{_pq:[],_pcache:new Map(),chars:[],mode:null,lob:null,_out:0,_clear(){},_lobRelease(){},stageL:null,stageR:null});return sc;}
test('studio uses existing effective shadowSize with historical2048 cap',async()=>{const f=await fixture();for(const quality of ['low','medium','high','ultra'])for(const touch of [false,true])for(const ios of [false,true]){const sc=rig(f,quality,{touch,ios}),expected=Math.min(2048,f.effectiveQuality({quality},{touch,ios}).shadowSize);assert.equal(sc.key.shadow.mapSize.x,expected);assert.equal(sc.key.shadow.mapSize.y,expected);assert.equal(sc.key.castShadow,true);}assert.equal(studioShadowSize({shadowSize:4096}),2048);});
test('cold G.mobile works before G.game, while a published Game profile has precedence',async()=>{const f=await fixture();f.G.settings={quality:'low'};f.G.game=null;f.G.mobile={touch:true};const sc=Object.create(f.Showcase.prototype);sc.scene=new f.THREE.Scene();sc._buildLights();assert.equal(sc.key.shadow.mapSize.x,1024);});
test('actual hidden render releases HIGH maps before early return; stable size never churns',async()=>{const f=await fixture(),sc=rig(f,'high'),{G,THREE}=f;let disposed=0;const m=new THREE.WebGLRenderTarget(2048,2048),p=new THREE.WebGLRenderTarget(2048,2048);m.addEventListener('dispose',()=>disposed++);p.addEventListener('dispose',()=>disposed++);sc.key.shadow.map=m;sc.key.shadow.mapPass=p;G.settings.quality='low';sc.render();assert.equal(disposed,2);assert.equal(sc.key.shadow.map,null);assert.equal(sc.key.shadow.mapPass,null);assert.equal(sc.key.shadow.mapSize.x,1024);assert.equal(sc.key.shadow.needsUpdate,true);const low=new THREE.WebGLRenderTarget(1024,1024);low.addEventListener('dispose',()=>disposed++);sc.key.shadow.map=low;for(let n=0;n<120;n++)sc.render();assert.equal(disposed,2);assert.equal(sc.key.shadow.map,low);G.settings.quality='high';sc.render();assert.equal(disposed,3);assert.equal(sc.key.shadow.mapSize.x,2048);});
function renderer(sc,THREE){let rt=null,alpha=.5;const calls=[];return{calls,autoClear:true,toneMappingExposure:1,shadowMap:{needsUpdate:false},getRenderTarget:()=>rt,setRenderTarget:v=>rt=v,getClearAlpha:()=>alpha,getClearColor:c=>c.set('blue'),setClearColor:(_c,a)=>alpha=a,clear(){},render(scene){if(scene===sc.scene){assert.equal(this.shadowMap.needsUpdate,true);calls.push(sc.key.shadow.mapSize.x);if(!sc.key.shadow.map)sc.key.shadow.map=new THREE.WebGLRenderTarget(sc.key.shadow.mapSize.x,sc.key.shadow.mapSize.y);}},readRenderTargetPixelsAsync:()=>Promise.resolve()};}
test('loadout/locker/results keep animated per-frame shadow updates at the budgeted resolution',async()=>{const f=await fixture(),sc=rig(f),r=renderer(sc,f.THREE);Object.assign(sc,{r,chars:[{}],fadeIn:1,_clr:new f.THREE.Color(),_target:()=>({texture:{}}),camera:{},compScene:{},compCam:{},compMat:{uniforms:{tMap:{},uOpacity:{}}},_cameraPedestal(){},_cameraResults(){}});for(const mode of ['loadout','locker','results']){sc.mode=mode;for(let n=0;n<60;n++){r.shadowMap.needsUpdate=false;sc.render();}}assert.equal(r.calls.length,180);assert(r.calls.every(x=>x===1024));assert.equal(r.autoClear,true);assert.equal(r.getRenderTarget(),null);assert.equal(r.getClearAlpha(),.5);});
test('direct native portrait uses the same LOW budget and preserves pending overlay shadow refresh',async()=>{const f=await fixture(),sc=rig(f,'high'),r=renderer(sc,f.THREE),T=f.THREE;class Char{constructor(){this.root=new T.Group();}setDance(){}update(){}getHeadPosition(o){o.set(0,1.8,0);}dispose(){}}Object.assign(sc,{r,mode:'loadout',CharacterClass:Char,color:new T.Color('orange'),_c:new T.Color(),_c2:new T.Color(),_clr:new T.Color(),_pv:new T.Vector3(),_anim:()=>({}),_prt:{},_prt8:{texture:{}},_pres:{uniforms:{tMap:{},uExposure:{}}},_presScene:{},compCam:{}});f.G.settings.quality='low';await sc._renderPortraitRun({color:'orange',style:{}},16,'head',r);assert.deepEqual(r.calls,[1024]);assert.equal(sc.key.shadow.map.width,1024);assert.equal(r.shadowMap.needsUpdate,true);assert.equal(r.getRenderTarget(),null);assert.equal(r.autoClear,true);});
test('native disposal releases both GPU targets exactly once and clears pointers',async()=>{const f=await fixture(),sc=rig(f);let n=0;sc.key.shadow.map={dispose(){n++}};sc.key.shadow.mapPass={dispose(){n++}};const portrait={width:16,height:16};sc._pcache.set('fixture',portrait);sc.dispose();sc.dispose();assert.equal(n,2);assert.equal(sc._pcache.size,0);assert.equal(portrait.width,0);assert.equal(portrait.height,0);assert.equal(sc.key.shadow.map,null);assert.equal(sc.key.shadow.mapPass,null);});
test('old native LOW path is a2048 negative control; missing/duplicate anchors fail closed',async()=>{const f=await fixture({baseline:true,built:null});assert.equal(rig(f).key.shadow.mapSize.x,2048);const raw=fs.readFileSync(path.join(ROOT,'inkwave-public/src/game/showcase.js'),'utf8'),needle='    key.shadow.mapSize.set(2048, 2048);';for(const replacement of ['',needle+'\n'+needle])assert.throws(()=>adaptQualitySource('src/game/showcase.js',raw.replace(needle,replacement)));});
test('shared map/pass handles are disposed once and stale physical target dimensions are repaired',()=>{let n=0;const target={width:2048,height:2048,dispose(){n++}},s={mapSize:{x:1024,y:1024,set(x,y){this.x=x;this.y=y;}},map:target,mapPass:target};assert(syncStudioShadow({shadow:s},{shadowSize:1024}));assert.equal(n,1);releaseStudioShadow({shadow:s});assert.equal(n,1);});
