import{fixture as weaponFixture}from '../../splatoon3/tests/weapon-edgecases-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import{fileURLToPath}from'node:url';
import{adaptSource}from'../../splatoon3/adapter.mjs';import{adaptTouchLayout}from'../../touch-layout/adapter.mjs';import{adaptReliability}from'../../reliability/adapter.mjs';import{adaptQualitySource}from'../adapter.mjs';
const ROOT=fileURLToPath(new URL('../../../',import.meta.url));
class El{constructor(){this.children=[];this.className='';this.style={setProperty(){}};this.dataset={};this.classList={add:(c)=>this.className+=' '+c,remove:()=>{},toggle:()=>{}};}appendChild(c){this.children.push(c);c.parent=this;return c;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);}querySelector(sel){if(!this.nodes)this.nodes=new Map();if(!this.nodes.has(sel))this.nodes.set(sel,new El());return this.nodes.get(sel);}insertAdjacentHTML(_where,html){this.inserted=html;}querySelectorAll(){return this.children.filter(c=>c.className?.includes('iw-call'));}addEventListener(){}setAttribute(){}get lastElementChild(){return this.children.at(-1);}get textContent(){return this.text||this.children.map(c=>c.textContent).join('');}set textContent(s){this.text=s;}set innerHTML(s){this.children=[];this.markup=s;this.nodes=new Map();} }
async function fixture(){const built=process.env.INKWAVE_SPLATLING_RETICLE_SITE,src=path.resolve(built||path.join(ROOT,'inkwave-public')),mods=new Map();const context=vm.createContext({console,performance,setTimeout:()=>1,clearTimeout(){},innerWidth:1280,innerHeight:720,localStorage:{getItem:()=>'{"lang":"en"}'},document:{documentElement:new El(),createElement:()=>new El(),createTextNode:text=>({textContent:text})}});
function load(file){if(mods.has(file))return mods.get(file);let code=fs.readFileSync(file,'utf8'),rel=path.relative(src,file);if(!built&&!rel.startsWith('..'))code=adaptQualitySource(rel,adaptReliability(rel,adaptTouchLayout(rel,adaptSource(rel,code))));const m=new vm.SourceTextModule(code,{context,identifier:file});mods.set(file,m);return m;}
const entry=new vm.SourceTextModule("export * from './src/core/ctx.js';export * from './src/game/match.js';export * from './src/ui/hud.js';export * from './src/net/netmatch.js';export * from './patches/local-quality/splatling-reticle.mjs';export * from './src/config.js';export * as THREE from 'three';",{context,identifier:path.join(src,'fixture.mjs')});await entry.link((spec,from)=>{let f=spec==='three'?path.join(src,'vendor/three/build/three.module.js'):spec.startsWith('three/addons/')?path.join(src,'vendor/three/jsm',spec.slice(13)):path.resolve(path.dirname(from.identifier),spec);if(!built)f=f.replace('/inkwave-public/patches/','/patches/');return load(f);});await entry.evaluate();const profile=JSON.parse(fs.readFileSync(path.join(built?src:ROOT,'patches/splatoon3/profile.json'),'utf8'));for(const [id,data]of Object.entries(profile.weapons))Object.assign(entry.namespace.WEAPONS[id],data);return entry.namespace;}

function rig(f){const h=Object.create(f.HUD.prototype),runner={streaming:false},a={team:0,alive:true,weapon:f.WEAPONS.splatling,weaponRunner:runner};f.G.match={local:a};Object.assign(h,{ret:new El(),xh:new El(),spIcon:new El(),shield:new El(),subChip:new El(),_L:{},_bloom:0,_kick:0,_restart(){}});return{h,a,runner,update:(c)=>h._updCrosshair({weapon:'splatling',charge:c},1/60)};}
const close=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('full native HUD builds two rings and follows48F/72F profile without weapon mutations',async()=>{const f=await fixture(),r=rig(f),before=JSON.stringify(r.a.weapon);for(const [frame,first,second]of [[0,0,0],[24,.5,0],[47,47/48,0],[48,1,0],[60,1,.5],[72,1,1]]){r.update(frame/72);close(r.h._L.splatFirst,first);close(r.h._L.splatSecond,second);close(+r.h._chargeEl.style.strokeDashoffset,Number((100*(1-first)).toFixed(2)));close(+r.h._chargeSecond.style.strokeDashoffset,Number((100*(1-second)).toFixed(2)));}assert.match(r.h.ret.querySelector('svg').inserted,/iw-ret__charge-second/);assert.equal(JSON.stringify(r.a.weapon),before);});
test('partial stream never jumps to full; both stages unwind against native remaining duration',async()=>{const f=await fixture(),r=rig(f),w=r.a.weapon;r.update(2/3);r.runner.streaming=true;r.runner.burstT=w.burstFirst;r.update(1);close(r.h._L.splatFirst,1);close(r.h._L.splatSecond,0);r.runner.burstT=w.burstFirst/2;r.update(.5);close(r.h._L.splatFirst,.5);close(r.h._L.splatSecond,0);r.runner.burstT=(w.burstMax+w.burstFirst)/2;r.update(.75);close(r.h._L.splatFirst,1);close(r.h._L.splatSecond,.5);r.runner.burstT=0;r.update(0);close(r.h._L.splatFirst,0);close(r.h._L.splatSecond,0);});
test('30/60/120Hz presentation reads the same fixed60Hz state and reuses progress storage',async()=>{const f=await fixture();for(const hz of [30,60,120]){const r=rig(f);for(let frame=0;frame<=72;frame++){if(hz!==30||frame%2===0)r.update(frame/72);if(hz===120)r.update(frame/72);if(frame===48){close(r.h._L.splatFirst,1);close(r.h._L.splatSecond,0);}}const out=r.h._splatStages;r.update(1);assert.equal(r.h._splatStages,out);close(r.h._L.splatSecond,1);}});
test('weapon switches rebuild stage nodes and reset scalar cache; Charger remains single ring',async()=>{const f=await fixture(),r=rig(f);r.update(1);const old=r.h._chargeSecond;r.h._updCrosshair({weapon:'charger',charge:.5},1/60);assert.equal(r.h._L.kind,'charger');assert(!r.h.ret.markup.includes('charge-second'));r.update(.25);assert.notEqual(r.h._chargeSecond,old);close(r.h._L.splatFirst,.375);close(r.h._L.splatSecond,0);});
test('invalid charge/profile fallback is bounded and anchors fail closed',async()=>{const f=await fixture();assert.equal(f.splatlingStages(NaN,null,{}).first,0);assert.equal(f.splatlingStages(Infinity,null,{}).second,0);const raw=fs.readFileSync(path.join(ROOT,'inkwave-public/src/ui/hud.js'),'utf8');assert.throws(()=>adaptQualitySource('src/ui/hud.js',raw.replace('this._chargeC = 100;','')));});

test('actual native S3 WeaponRunner48/72F and partial/full releases feed HUD unchanged',async()=>{for(const release of [48,72]){const f=await fixture(),r=rig(f),wf=await weaponFixture(),a=wf.make('splatling');f.G.match.local=a;a.intent.fire=true;for(let frame=1;frame<=release;frame++){wf.tick(a);r.update(a.weaponRunner.charge);if(frame===48){close(r.h._L.splatFirst,1);close(r.h._L.splatSecond,0);}}close(r.h._L.splatSecond,release===72?1:0);a.intent.fire=false;wf.tick(a);close(a.weaponRunner.burstDur,release===72?a.weapon.burstMax:a.weapon.burstFirst);r.update(a.weaponRunner.charge);close(r.h._L.splatSecond,release===72?1:0);wf.tick(a);r.update(a.weaponRunner.charge);assert(r.h._L.splatSecond<= (release===72?1:0));}});
test('partial releases show actual paid4F slots when reservation patch is composed',async()=>{for(const [frames,baseFirst,baseSecond,slotFirst,slotSecond]of [[24,.5,0,.5,0],[47,47/48,0,1,0],[49,1,1/24,1,.05],[71,1,23/24,1,1]]){const f=await fixture(),r=rig(f),wf=await weaponFixture(),a=wf.make('splatling');f.G.match.local=a;a.intent.fire=true;wf.tick(a,frames);r.update(a.weaponRunner.charge);close(r.h._L.splatFirst,baseFirst);close(r.h._L.splatSecond,baseSecond);a.intent.fire=false;wf.tick(a);r.update(a.weaponRunner.charge);const reserved=typeof wf.splatlingReservation==='function';close(r.h._L.splatFirst,reserved?slotFirst:baseFirst);close(r.h._L.splatSecond,reserved?slotSecond:baseSecond);assert.equal(a.weaponRunner.streaming,true);}});
