import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import{fileURLToPath}from'node:url';
import{adaptSource}from'../../splatoon3/adapter.mjs';import{adaptTouchLayout}from'../../touch-layout/adapter.mjs';import{adaptReliability}from'../../reliability/adapter.mjs';import{adaptQualitySource}from'../adapter.mjs';
const ROOT=fileURLToPath(new URL('../../../',import.meta.url));
class El{constructor(){this.children=[];this.className='';this.style={setProperty(){}};this.dataset={};this.classList={add:(c)=>this.className+=' '+c,remove:()=>{},toggle:()=>{}};}appendChild(c){this.children.push(c);c.parent=this;return c;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);}querySelectorAll(){return this.children.filter(c=>c.className?.includes('iw-call'));}addEventListener(){}setAttribute(){}get lastElementChild(){return this.children.at(-1);}get textContent(){return this.text||this.children.map(c=>c.textContent).join('');}set textContent(s){this.text=s;}set innerHTML(s){this.children=[];} }
async function fixture(){const built=process.env.INKWAVE_WIPEOUT_BUILT_SITE,src=path.resolve(built||path.join(ROOT,'inkwave-public')),mods=new Map();const context=vm.createContext({console,performance,setTimeout:()=>1,clearTimeout(){},innerWidth:1280,innerHeight:720,localStorage:{getItem:()=>'{"lang":"en"}'},document:{documentElement:new El(),createElement:()=>new El(),createTextNode:text=>({textContent:text})}});
function load(file){if(mods.has(file))return mods.get(file);let code=fs.readFileSync(file,'utf8'),rel=path.relative(src,file);if(!built&&!rel.startsWith('..'))code=adaptQualitySource(rel,adaptReliability(rel,adaptTouchLayout(rel,adaptSource(rel,code))));const m=new vm.SourceTextModule(code,{context,identifier:file});mods.set(file,m);return m;}
const entry=new vm.SourceTextModule("export * from './src/core/ctx.js';export * from './src/game/match.js';export * from './src/ui/hud.js';export * from './src/net/netmatch.js';export * from './patches/local-quality/team-wipeout.mjs';export * as THREE from 'three';",{context,identifier:path.join(src,'fixture.mjs')});await entry.link((spec,from)=>{let f=spec==='three'?path.join(src,'vendor/three/build/three.module.js'):spec.startsWith('three/addons/')?path.join(src,'vendor/three/jsm',spec.slice(13)):path.resolve(path.dirname(from.identifier),spec);if(!built)f=f.replace('/inkwave-public/patches/','/patches/');return load(f);});await entry.evaluate();return entry.namespace;}
function rig(f){const m=new f.Match({});m.actors=Array.from({length:8},(_,i)=>({team:i>>2,alive:true,name:'P'+i,pos:new f.THREE.Vector3(i*10,0,0),update(){},net:{}}));m.local=m.actors[0];f.G.match=m;f.G.mode='match';m.start();m.setState('playing');const h=Object.create(f.HUD.prototype),sounds=[],cards=[];Object.assign(h,{el:new El(),overLayer:new El(),callouts:new El(),_t:0,_fxTime:1,_L:{ca:'#ff8a14',cb:'#2f5bff'},_kills:{times:[],streak:0,dealt:new Map()},boss:{on:false,update(){}},playSound:n=>sounds.push(n),_killCard:(v,k)=>cards.push(k),_allyDown(){},_clearDamageDirs(){},_restart(){}});for(const name of ['Timer','Squads','Crosshair','Tank','Special','Turf','Hp','Map','Markers','DamageDirs','Downs','Prompt','Fps'])h['_upd'+name]=()=>{};h._bindBus();return{m,h,sounds,cards,tick:()=>{m.update(1/60);h.update(1/60,{});}};}
function wipe(m,team){m.actors.filter(a=>a.team===team).forEach(a=>a.alive=false);}
test('native Match→bus→HUD emits teammate-finished, own-team, and repeated transitions once',async()=>{const f=await fixture(),r=rig(f),ev=[];f.on('team:wipeout',e=>ev.push(e));wipe(r.m,1);r.tick();assert.equal(ev.length,1);assert.equal(r.h.callouts.lastElementChild.textContent,'WIPEOUT!!!The whole team is splatted');assert.match(r.h.callouts.lastElementChild.className,/is-enemy-wipeout/);for(let i=0;i<120;i++)r.tick();assert.equal(r.sounds.length,1);wipe(r.m,0);r.tick();assert.equal(ev.length,2);assert.equal(r.sounds.at(-1),'defeat_jingle');assert.match(r.h.callouts.lastElementChild.className,/is-own-wipeout/);const a=r.m.actors[4];f.NetMatch.prototype._remoteRespawn.call({match:r.m},a);a.alive=false;r.tick();assert.equal(ev.length,3);assert.equal(r.sounds.at(-1),'special_ready');});
test('local killer and assists retain bookkeeping; queued team message wins once',async()=>{const f=await fixture(),r=rig(f),v=r.m.actors[7];wipe(r.m,1);f.emit('splatted',{victim:v,attacker:r.m.local});r.tick();assert.deepEqual(r.cards,['kill']);assert.equal(r.h._kills.streak,1);assert.equal(r.sounds.filter(s=>s==='special_ready').length,1);assert.match(r.h.callouts.lastElementChild.textContent,/WIPEOUT!!!/);const a=r.m.actors[4];a.alive=true;f.rearmTeamWipe(r.m,a);r.h._kills.dealt.set(a,1);a.alive=false;f.emit('splatted',{victim:a,attacker:r.m.actors[1]});r.tick();assert.deepEqual(r.cards,['kill','assist']);assert.equal(r.sounds.filter(s=>s==='special_ready').length,2);});
test('simultaneous wipe reports both but HUD prioritizes own-team danger',async()=>{const f=await fixture(),r=rig(f),ev=[];f.on('team:wipeout',e=>ev.push(e.team));wipe(r.m,0);wipe(r.m,1);r.tick();assert.deepEqual(ev,[0,1]);assert.deepEqual(r.sounds,['defeat_jingle']);});
test('pause, finished state, partial roster, Boss and attract do not notify',async()=>{for(const mode of ['paused','finish','partial','boss','attract']){const f=await fixture(),r=rig(f);if(mode==='paused')r.m.paused=true;if(mode==='finish')r.m.state='finish';if(mode==='partial')r.m.actors.pop();if(mode==='boss')r.m.mode='boss';if(mode==='attract')r.m.attract=true;wipe(r.m,1);r.tick();assert.equal(r.sounds.length,0,mode);}});
test('stale/duplicate events and old match pending messages cannot leak',async()=>{const f=await fixture(),r=rig(f),e={match:r.m,team:1,sequence:1};f.emit('team:wipeout',e);f.emit('team:wipeout',e);r.h.update(.01,{});f.emit('team:wipeout',e);r.h.update(.01,{});assert.equal(r.sounds.length,1);f.emit('team:wipeout',{...e,sequence:2});f.G.match={...r.m};r.h.update(.01,{});assert.equal(r.sounds.length,1);f.emit('team:wipeout',{...e,sequence:3});r.h.update(.01,{});assert.equal(r.sounds.length,1);});
test('HUD lifecycle reset drops queued events and ordinary callout sound stays unchanged',async()=>{const f=await fixture(),r=rig(f);f.emit('team:wipeout',{match:r.m,team:1,sequence:1});Object.assign(r.h,{kcards:new El(),tpops:new El(),downLayer:new El(),turfNum:new El(),_lineup(){}});r.h.boss.setMode=()=>{};r.h._startMatchHud(r.m);r.h.update(.01,{});assert.equal(r.sounds.length,0);r.h._callout('FIRST SPLAT!',null,false);assert.equal(r.sounds.at(-1),'ui_confirm');r.h._callout('TRIPLE!',null,true);assert.equal(r.sounds.at(-1),'special_ready');});
test('local rearm and mutable teamSummary transport never retain previous-frame objects',async()=>{const f=await fixture(),r=rig(f);const frame={teams:[{players:[]},{players:[]}]};wipe(r.m,1);r.m.update(.01);r.h.update(.01,frame);const a=r.m.actors[4];a.alive=true;f.rearmTeamWipe(r.m,a);a.alive=false;frame.teams[1].players.length=0;r.m.update(.01);r.h.update(.01,frame);assert.equal(r.sounds.length,2);});
test('missing adapter anchors fail closed and old local-killer branch is removed',()=>{const raw=fs.readFileSync(path.join(ROOT,'inkwave-public/src/ui/hud.js'),'utf8');assert(raw.includes("enemies.every((a) => !a.alive)"));const fixed=adaptQualitySource('src/ui/hud.js',raw);assert(!fixed.includes('enemies.every'));assert.throws(()=>adaptQualitySource('src/ui/hud.js',raw.replace('  _callout(text, sub, big) {','')));});

test('#593 Turf suppresses each personal streak ribbon without losing direct kill cards',async()=>{
 for(const state of ['first','double','triple','quad','revenge','shutdown','streak3','streak5']){
  const f=await fixture(),r=rig(f),v=r.m.actors[4],K=r.h._kills;
  K.first=state!=='first';K.times=state==='double'?[.5]:state==='triple'?[.4,.5]:state==='quad'?[.3,.4,.5]:[];
  K.streak=state==='streak3'?2:state==='streak5'?4:0;K.lastKiller=state==='revenge'?v:null;
  K.perActor=new Map([[v,state==='shutdown'?3:0]]);
  const before=K.streak,observed=[];f.on('splatted',e=>observed.push(e));
  f.emit('splatted',{victim:v,attacker:r.m.local});
  assert.deepEqual(r.cards,['kill'],state);assert.equal(K.streak,before+1,state);
  assert.equal(observed.length,1,'independent event consumers still receive the event');
  assert.equal(r.h.callouts.children.length,0,state);assert.equal(r.sounds.length,0,state);
 }
});
test('#593 local death cleanup and non-Turf original presentation remain available',async()=>{
 const f=await fixture(),r=rig(f);let cleared=0;r.h._clearDamageDirs=()=>cleared++;
 f.emit('splatted',{victim:r.m.local,attacker:r.m.actors[4]});assert.equal(cleared,1);assert.equal(r.h._kills.lastKiller,r.m.actors[4]);
 r.m.mode='boss';r.h._kills.first=false;f.emit('splatted',{victim:r.m.actors[4],attacker:r.m.local});
 assert.equal(r.h.callouts.children.length,1);assert.match(r.h.callouts.lastElementChild.textContent,/FIRST SPLAT/);
});
