import test from 'node:test';
import assert from 'node:assert/strict';
import {pair,advanceMillis} from './hidden-host-harness.mjs';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('Refs878 same host resumes after 0.1/5/20/120 seconds without physics or G.time catch-up',async()=>{
 for(const seconds of [.1,5,20,120]){const p=await pair();try{const before=p.host.snapshot(),time=p.host.f.G.time;p.host.hide(true);p.frames(seconds);assert.equal(p.host.m.time,10);assert.equal(p.host.snapshot().physics,before.physics);assert.equal(p.host.snapshot().raf,0);if(seconds>=10){assert.equal(p.guest.m.time,0);assert.equal(p.guest.m.state,'playing','permanent hidden guest limitation remains');}p.host.hide(false);close(p.host.m.time,Math.max(0,10-seconds));assert.equal(p.host.m.state,seconds>=10?'finish':'playing');if(seconds>=10)assert.equal(p.guest.m.state,'finish','native host-state event reaches follower on resume');assert.equal(p.host.f.G.time,time);assert.equal(p.host.snapshot().physics,before.physics);assert.equal(p.host.game.s3Clock?.accumulator??0,0);}finally{p.close();}}
});
test('Refs878 repeated short switches and duplicate visibility delivery consume each interval once',async()=>{const p=await pair();try{for(let i=0;i<3;i++){p.host.hide(true);advanceMillis(100);p.host.hide(false);const t=p.host.m.time;p.host.hide(false);p.host.env.dispatchEvent(new Event('focus'));close(p.host.m.time,t);}close(p.host.m.time,9.7);assert.equal(p.host.game.platform.hiddenHostClock,null);}finally{p.close();}});
test('Refs878 already-finished match is never re-timed on resume',async()=>{const p=await pair();try{p.host.hide(true);p.host.m.setState('finish');advanceMillis(5000);p.host.hide(false);assert.equal(p.host.m.state,'finish');assert.equal(p.host.m.time,10);}finally{p.close();}});
test('Refs878 replacement match or NetMatch is not touched by an old suspended record',async()=>{for(const kind of ['match','net']){const p=await pair();try{p.host.hide(true);advanceMillis(5000);if(kind==='match')p.host.game.match=new p.host.f.Match({duration:90});else p.host.f.G.netm={};p.host.hide(false);assert.equal(p.host.m.time,10);if(kind==='match')assert.equal(p.host.game.match.time,90);}finally{p.close();}}});
test('Refs878 owner change and real relay disconnect/migration invalidate the old host record',async()=>{const p=await pair();try{p.host.hide(true);p.frames(20);p.host.socket.close();p.frames(1/60);assert.equal(p.guest.s.isHost,true);assert.equal(p.guest.m.follower,false);assert.equal(p.guest.m.state,'finish');p.host.hide(false);assert.equal(p.host.m.time,10);assert.equal(p.host.s.state,'error');assert.equal(p.host.snapshot().aborted,1);}finally{p.close();}const q=await pair();try{q.host.hide(true);advanceMillis(5000);q.host.s.hostId=q.guest.s.myId;q.host.hide(false);assert.equal(q.host.m.time,10);}finally{q.close();}});
test('Refs878 excludes guest, offline, Boss, attract and paused scopes',async()=>{for(const kind of ['guest','offline','boss','attract','paused']){const p=await pair();try{const h=kind==='guest'?p.guest:p.host;if(kind==='offline')h.s.state='offline';if(kind==='boss')h.m.mode='boss';if(kind==='attract')h.m.attract=true;if(kind==='paused')h.m.paused=true;h.hide(true);advanceMillis(5000);h.hide(false);assert.equal(h.m.time,10,kind);}finally{p.close();}}});
test('Refs878 invalid/reversed monotonic time cannot increase or invent elapsed time',async()=>{for(const kind of ['reverse','invalid']){const p=await pair();try{p.host.hide(true);if(kind==='reverse')advanceMillis(-1000);else p.host.env.performance.now=()=>NaN;p.host.hide(false);assert.equal(p.host.m.time,10);}finally{p.close();}}});
test('Refs878 legitimate separate clock advance cannot be rolled back or subtracted twice',async()=>{const p=await pair();try{p.host.hide(true);p.host.m.time=3;advanceMillis(1000);p.host.hide(false);assert.equal(p.host.m.time,3);p.host.hide(false);assert.equal(p.host.m.time,3);}finally{p.close();}});
