import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';
import {boot,pad,STEP}from'./pause-fixture.mjs';
import {PlatformLifecycle,getPlatformLifecycle}from'../../local-quality/platform-lifecycle.mjs';
const lifecycleSource=fs.readFileSync(new URL('../../local-quality/platform-lifecycle.mjs',import.meta.url),'utf8');
const initialFocusBlock="    // Visibility and focus are independent at construction (for example, iframes).\n    // Keep legacy hosts without hasFocus usable; a failed query cannot grant input.\n    try { this.focused = typeof env.document?.hasFocus === 'function' ? !!env.document.hasFocus() : true; }\n    catch { this.focused = false; }\n";
assert.equal(lifecycleSource.split(initialFocusBlock).length,2);
const {PlatformLifecycle:OldLifecycle}=await import('data:text/javascript;base64,'+Buffer.from(lifecycleSource.replace(initialFocusBlock,'    this.focused = true;\n')).toString('base64'));
import {installInputPlatform}from'../../local-quality/platform-input.mjs';
// Use the old input wrapper with the corrected lifecycle for the isolated second negative.
const inputSource=fs.readFileSync(new URL('../../local-quality/platform-input.mjs',import.meta.url),'utf8');
const initialRebaseBlock="    // Remember initial unfocus even if focus arrives before the first poll.\n    if (this._platformPadBlurEpoch === undefined && !initiallyFocused) {\n      this._platformPadBlurEpoch = initialBlur;\n      this._padEpoch = (this._padEpoch || 0) + 1;\n      this._platformPadFocusRebase = true;\n      this._platformPadRebase = this._platformPadAxes = true;\n    }\n";
assert.equal(inputSource.split(initialRebaseBlock).length,2);
const oldInputCode=inputSource.replace(initialRebaseBlock,'').replace("'./platform-lifecycle.mjs'",JSON.stringify(new URL('../../local-quality/platform-lifecycle.mjs',import.meta.url).href));
const {installInputPlatform:oldInput}=await import('data:text/javascript;base64,'+Buffer.from(oldInputCode).toString('base64'));
function env({focused=false,hidden=false,missing=false,throws=false}={}){const e=new EventTarget();e.document=new EventTarget();e.document.hidden=hidden;if(!missing)e.document.hasFocus=function(){assert.equal(this,e.document);if(throws)throw Error('unavailable');return focused;};e.screen={orientation:new EventTarget()};e.performance=performance;return e;}
const active=()=>{const p=pad([0,3,5,6,7,11]);p[0].axes=[.8,-.5,.9,.6,-1];p[0].buttons[7]={pressed:false,value:.4};return p;};
async function setup(options={},install=installInputPlatform){const h=await boot(),e=env(options);install(h.input.constructor,e);h.input.lastDevice='touch';return {...h,e,owner:getPlatformLifecycle(e),poll(){h.input.pollPad();h.controller.update(STEP);},signal(n){e.dispatchEvent(new Event(n));}};}
function neutral(h){assert.equal(h.rig.yaw,0);assert.equal(h.rig.pitch,0);assert.equal(h.actor.intent.move.length(),0);for(const a of ['fire','jump','squid','sub','special'])assert.equal(h.actor.intent[a],false,a);assert.equal(h.input.padPressed.size,0);assert.equal(h.input.padMenuPressed.size,0);assert.equal(h.input.lastDevice,'touch');}
test('old lifecycle invents focus; corrected initialization samples actual focus without a blur',()=>{const e=env();const old=new OldLifecycle(e);assert.equal(old.focused,true);old.dispose();const n=new PlatformLifecycle(e);assert.equal(n.focused,false);assert.equal(n.active,true);assert.equal(n.metrics.blurs,0);n.dispose();});
for(const hz of [30,60,120])for(const pollBeforeFocus of [false,true])test(`${hz}Hz initially unfocused, pre-focus polling=${pollBeforeFocus}: held gate and fresh recovery`,async()=>{const h=await setup();try{h.setPads(active());assert.equal(h.owner.focused,false);assert.equal(h.owner.state,'ACTIVE');if(pollBeforeFocus)for(let i=0;i<hz/2;i++){h.poll();h.frame(1/hz);neutral(h);}h.signal('focus');for(let i=0;i<3;i++){h.poll();neutral(h);}const epoch=h.input._padEpoch;h.poll();assert.equal(h.input._padEpoch,epoch);h.setPads(pad());h.poll();h.input.endFrame();h.setPads(active());h.poll();assert.ok(h.actor.intent.fire);assert.ok(h.actor.intent.move.length()>0);assert.notEqual(h.rig.yaw,0);assert.equal(h.input.lastDevice,'pad');assert.equal(h.owner.metrics.blurs,0);}finally{h.owner.dispose();}});
test('lifecycle-only fix still admits held input if focus precedes the first poll',async()=>{const h=await setup({},oldInput);try{h.setPads(active());h.signal('focus');h.poll();assert.ok(h.actor.intent.fire);assert.notEqual(h.rig.yaw,0);assert.ok(h.input.padPressed.size);}finally{h.owner.dispose();}});
test('focused startup preserves initial fresh input, hidden startup remains suspended, fallback is explicit',async()=>{const h=await setup({focused:true});try{h.setPads(active());h.poll();assert.ok(h.actor.intent.fire);assert.notEqual(h.rig.yaw,0);}finally{h.owner.dispose();}for(const spec of [{focused:false,hidden:true},{focused:true,hidden:true}]){const o=new PlatformLifecycle(env(spec));assert.equal(o.state,'SUSPENDED');assert.equal(o.active,false);o.dispose();}const legacy=new PlatformLifecycle(env({missing:true}));assert.equal(legacy.focused,true);legacy.dispose();const denied=new PlatformLifecycle(env({throws:true}));assert.equal(denied.focused,false);denied.dispose();});
test('repeated focus/blur preserves owners and #780 held return without epoch inflation',async()=>{const h=await setup();try{const before=h.owner.snapshot();h.setPads(active());for(let i=0;i<20;i++){h.signal('focus');h.poll();neutral(h);h.signal('blur');h.poll();neutral(h);}const after=h.owner.snapshot();assert.equal(after.listeners,before.listeners);assert.equal(after.subscribers,before.subscribers);assert.equal(after.blurs,20);assert.equal(after.errors,0);}finally{h.owner.dispose();}});
