import test from 'node:test';
import assert from 'node:assert/strict';
import {boot} from './pen-input-fixture.mjs';
import {adoptCanvasTouch,continueCanvasTouch,isMobilePointer} from '../../local-quality/first-touch-adapter.mjs';
function event(h,kind='fire',id=1,type='pen'){h.mobile._hitButton=()=>kind==='fire'?'fire':null;return {pointerType:type,pointerId:id,target:h.canvas,clientX:kind==='stick'?100:700,clientY:kind==='stick'?500:250,type:'pointerdown',preventDefault(){},stopPropagation(){}};}
const owned=(h,e)=>h.mobile._ptr.has(e.pointerId)||h.mobile._stick.id===e.pointerId;
function down(h,e){h.event('pointerdown',e);return adoptCanvasTouch(h.mobile,e);}
test('#852 old finger-only capture leaves pen behind both non-mobile owners',async()=>{for(const owner of ['kbm','pad']){const h=await boot({legacyPen:true});h.input.lastDevice=owner;const e=event(h);h.event('pointerdown',e);assert.equal(h.input.lastDevice,owner);assert.equal(h.mobile.root.classList.contains('is-active'),false);assert.equal(e.pointerType==='touch'&&adoptCanvasTouch(h.mobile,e),false);assert.equal(owned(h,e),false);}});
test('#852 pen reacquires both owners and routes fire/stick/look exactly once',async()=>{for(const owner of ['kbm','pad'])for(const kind of ['fire','stick','look']){const h=await boot();h.input.lastDevice=owner;const e=event(h,kind);assert.equal(h.mobile.root.classList.contains('is-active'),false);assert.equal(down(h,e),true);assert.equal(h.input.lastDevice,'touch');assert.equal(h.mobile.root.classList.contains('is-active'),true);assert.equal(owned(h,e),true);assert.equal(adoptCanvasTouch(h.mobile,e),false);if(kind==='fire')assert.equal(h.mobile.down('fire'),true);assert.equal(continueCanvasTouch(h.mobile,{...e,type:'pointermove',clientX:e.clientX+15},false),true);assert.equal(continueCanvasTouch(h.mobile,{...e,type:'pointerup'},true),true);assert.equal(owned(h,e),false);}});
test('#852 cancel and lost capture clear pen through native router',async()=>{for(const type of ['pointercancel','lostpointercapture'])for(const kind of ['fire','stick','look']){const h=await boot();const e=event(h,kind);down(h,e);assert.equal(continueCanvasTouch(h.mobile,{...e,type},true),true);assert.equal(owned(h,e),false);assert.equal(h.mobile.down('fire'),false);assert.equal(continueCanvasTouch(h.mobile,{...e,type},true),false);}});
test('#852 mouse/unknown pointers never enter direct-mobile path; finger remains accepted',async()=>{const h=await boot();for(const type of ['mouse','','unknown']){const e=event(h,'fire',40,type);assert.equal(isMobilePointer(e),false);assert.equal(adoptCanvasTouch(h.mobile,e),false);}assert.equal(isMobilePointer(null),false);const e=event(h,'fire',41,'touch');assert.equal(down(h,e),true);h.release(e);assert.equal(h.mobile.down('fire'),false);});
test('#852 existing Map/edit/visibility/hidden/disposal restrictions still reject pen',async()=>{for(const key of ['mapOpen','editing','hidden','invisible','disabled','destroyed','aborted']){const h=await boot();const e=event(h);if(key==='hidden')h.doc.hidden=true;else if(key==='invisible')h.mobile.visible=false;else if(key==='disabled')h.input.enabled=false;else if(key==='destroyed')h.mobile._destroyed=true;else if(key==='aborted')h.mobile._abort.abort();else h.mobile[key]=true;assert.equal(adoptCanvasTouch(h.mobile,e),false,key);assert.equal(owned(h,e),false,key);}});
test('#852 repeated owner transitions preserve listeners and live pen excludes mouse',async()=>{const h=await boot();const count=h.listenerCount();for(let i=0;i<20;i++){h.input.lastDevice=i%2?'kbm':'pad';const e=event(h,'fire',i+1);assert.equal(down(h,e),true);h.unlocked();h.mouse();assert.equal(h.input.lastDevice,'touch');assert.equal(h.mobile.down('fire'),true);h.release(e);h.mouse();assert.equal(h.input.lastDevice,'kbm');assert.equal(h.mobile._ptr.size,0);assert.equal(h.listenerCount(),count);}});
