import test from 'node:test';import assert from 'node:assert/strict';import {fixture} from './controls-fixture.mjs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const {resetPlatformInput}=await import(process.env.INKWAVE_CONTROLS_SITE?pathToFileURL(path.resolve(process.env.INKWAVE_CONTROLS_SITE,'patches/local-quality/platform-input.mjs')).href:new URL('../../local-quality/platform-input.mjs',import.meta.url).href);
async function setup(){const f=await fixture(),input=new f.Input({}),a=f.make(),c=new f.PlayerController(a,{yaw:0,pitch:0},input);c.computeAim=()=>{};f.G.settings={...f.DEFAULT_SETTINGS,aimAssist:0};f.G.actors=[a];f.G.level.spawnPads=[new f.THREE.Vector3()];f.G.physics.groundProbe=(_x,_y,_z,_r,_d,_foot,h)=>{h.hit=false;return h;};return{...f,input,a,c};}
test('platform reset cancels the dead pad-map reservation before resume or landing can revive it',async()=>{
 const f=await setup();f.a.alive=false;f.c.navigationEnabled=true;f.input.lastDevice='pad';f.input.pad={mapping:'standard'};f.c.padMapOpen=true;f.c.updateRespawnNavigation();assert.equal(f.c.requestMapJump(new f.THREE.Vector3(2,0,0)),true);assert.ok(f.c.pendingRespawnJump);
 resetPlatformInput(f.input,f.c);assert.equal(f.c.pendingRespawnJump,null);assert.equal(f.c.padMapOpen,false);assert.equal(f.c.mapHeld,false);assert.equal(f.c._respawnNavigationActive,false);
 f.input.pad={mapping:'standard'};f.input.lastDevice='pad';f.c.updateRespawnNavigation();assert.equal(f.c.mapHeld,false);assert.equal(f.c.pendingRespawnJump,null);f.a.respawn();f.a.grounded=true;f.c.updateRespawnNavigation();assert.equal(f.a.superJumpState,null);
});
for(const button of [6,7])test(`platform trigger${button} rebase uses canonical0.3 admission until real release`,async()=>{
 const f=await setup(),pad={connected:true,mapping:'standard',axes:[0,0,0,0],buttons:Array.from({length:17},(_,i)=>({pressed:false,value:i===button?.4:0}))};f.setPads([pad]);resetPlatformInput(f.input,f.c);
 for(let i=0;i<20;i++){f.input.pollPad();assert.equal(f.input.padPressed.has(button),false);assert.equal(f.input.padMenuPressed.has(button),false);assert.equal(f.input.padValue(button),0);f.c.update(1/60);assert.equal(f.a.intent[button===7?'fire':'squid'],false);}
 pad.buttons[button].value=.3;f.input.pollPad();assert.equal(f.input.padPressed.has(button),false);assert.equal(f.input.padMenuBlocked.has(button),false);pad.buttons[button].value=.4;f.input.pollPad();assert.equal(f.input.padPressed.has(button),true);assert.equal(f.input.padValue(button),.4);f.c.update(1/60);assert.equal(f.a.intent[button===7?'fire':'squid'],true);
});
